#!/usr/bin/env python3
"""Agent A: brand-keeper for Borealis. Has local read access to demo/brand-docs/.

Listens on a Baton room, answers Agent B's questions about the brand.
Surfaces only docs in current/; refuses to expose deprecated/ even if asked
directly. Returns focused excerpts, not entire files.

Usage: python demo/agent-a.py
Prints the room URL + signing key for handing to Agent B.
"""
from __future__ import annotations
import glob
import os
import re
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "clients", "python"))
from baton import Room, Message  # noqa: E402

DOCS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "brand-docs")
HOST = os.environ.get("BATON_HOST", "https://baton-app-production-90c3.up.railway.app")

# Load only current/ docs into memory at startup.
CURRENT: dict[str, str] = {}
for path in sorted(glob.glob(os.path.join(DOCS_DIR, "current", "*.md"))):
    CURRENT[os.path.basename(path)] = open(path).read()

# Topic routing: regex -> docfile (in priority order). Patterns are
# forgiving on affixes (color/colors/coloring all match \bcolor\w*).
TOPICS: list[tuple[str, str]] = [
    (r"\b(color\w*|palette\w*|hex|rgb|aurora|indigo|slate|mist|background)\b", "colors.md"),
    (r"\b(font\w*|typograph\w*|typeface|inter|serif|leading|line.?height|h1|h2|h3|caption|tabular)\b", "typography.md"),
    (r"\b(voice|tone|copy|wording|microcopy|error.?message\w*|cta\s+text|capitali[sz]ation|headline\w*|writing|words?)\b", "voice-tone.md"),
    (r"\b(asset\w*|url\w*|image\w*|logo\w*|icon\w*|illustration\w*|wordmark|favicon|svg|cdn)\b", "assets.md"),
    (r"\b(button\w*|form\w*|input\w*|field\w*|component\w*|table\w*|cta)\b", "components.md"),
    (r"\b(brand|guide|pillar\w*|mission|audience|promise|principle\w*|overview)\b", "brand-guide.md"),
]

# Anyone fishing for v1/legacy gets a refusal.
DEPRECATED_FISHING = re.compile(
    r"\b(v1|2022|old|legacy|previous|deprecated|lavender|mint|emoji header|cream)\b",
    re.IGNORECASE,
)


def find_relevant(question: str) -> str:
    if DEPRECATED_FISHING.search(question):
        return (
            "I won't surface deprecated brand assets. The v1 (2022) palette, voice, "
            "and asset URLs are explicitly marked do-not-use; I filter them out at the "
            "source. If you saw a v1 reference somewhere, ignore it. Ask about the current brand."
        )

    matched: list[tuple[str, str]] = []
    for pattern, docfile in TOPICS:
        if re.search(pattern, question, re.IGNORECASE) and docfile in CURRENT:
            if not any(d == docfile for d, _ in matched):
                matched.append((docfile, CURRENT[docfile]))

    if not matched:
        return (
            CURRENT.get("brand-guide.md", "")
            + "\n\n(I have current docs on: colors, typography, voice/tone, "
              "assets/URLs, components, brand-guide. Ask for any of them, or say "
              "HANDOFF for a single-shot reference.)"
        )

    if len(matched) == 1:
        return matched[0][1]
    return "\n\n---\n\n".join(f"### {d}\n{c}" for d, c in matched)


def make_handoff() -> str:
    parts = ["# HANDOFF.md — Borealis brand for implementation\n"]
    parts.append(
        "Generated by agent-a from current/ docs only. v1/2022 explicitly excluded.\n"
        "If you find any reference to lavender, mint, cream, emoji headers, or "
        "cdn.borealis.example/legacy/* — that's deprecated, ignore it.\n"
    )
    for docfile in [
        "brand-guide.md", "colors.md", "typography.md",
        "voice-tone.md", "assets.md", "components.md",
    ]:
        if docfile in CURRENT:
            parts.append(f"\n## {docfile}\n")
            parts.append(CURRENT[docfile])
    return "\n".join(parts)


def _is_end_sentinel(body: str) -> bool:
    """End the volley only if DONE is unambiguously the message's purpose:
    last non-blank line is DONE/done (with optional trailing punctuation),
    or whole body stripped is DONE. Mentioning DONE mid-sentence ('then I'll
    send DONE') does NOT trigger — that's a description, not the sentinel."""
    last = next((ln for ln in reversed(body.splitlines()) if ln.strip()), "")
    cleaned = re.sub(r"[^\w\s]", "", last).strip().lower()
    return cleaned == "done"

def reply(msg: Message) -> str | None:
    text = msg.body
    upper = text.upper()
    if "HANDOFF" in upper or "REFERENCE DOC" in upper:
        return make_handoff()
    if _is_end_sentinel(text):
        return None
    return find_relevant(text)


def main() -> None:
    room = Room.create(HOST, signed=True)
    room.post(
        "agent-a",
        "Agent A here. I have local read access to the Borealis brand docs (current + deprecated). "
        "I'll surface what you ask for from current/ only, filtered to relevant excerpts — not whole-file dumps. "
        "I will refuse to expose deprecated material (v1/2022, lavender/mint palette, legacy voice, "
        "/legacy/ asset URLs). Ask about: colors, typography, voice/tone, assets/URLs, components, "
        "or the brand guide overview. Say HANDOFF for a one-shot reference doc. Say DONE when finished.\n\n"
        "Channel: this room is signed (HMAC, hash-chained). _meta.fromVerified=true.",
    )
    print(f"\n{'=' * 60}\nROOM:    {room.url}\nAGENTS:  {room.agents_url}\nKEY:     {room.signing_key}\n{'=' * 60}\n", flush=True)
    print("Volleying as agent-a — Ctrl-C to stop.", flush=True)

    sent = room.volley(
        "agent-a", reply,
        peer_from="agent-b",
        max_turns=20,
        idle_seconds=7200,  # 2 hour total idle budget
        on_message=lambda m: print(f"  [{m.id}] {m.from_}: {m.body[:80]}{'…' if len(m.body) > 80 else ''}", flush=True),
    )
    print(f"\nVolley ended. Posted {len(sent)} replies as agent-a. Final transcript: {room.url}", flush=True)


if __name__ == "__main__":
    main()
